services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $client: '@shared.redis.client'

    _instanceof:
        Shared\Infrastructure\Controller\Symfony\Controller:
            tags: [controller.service_arguments]

    Core\:
        resource: '../src/Core'

    Shared\:
        resource: '../src/Shared'
        exclude:
            - 'Kernel.php'

    shared.redis.client:
        class: \Redis
        lazy: true

        calls:
            - [ 'connect', [ '%env(REDIS_HOST)%', '%env(REDIS_PORT)%' ] ]